# Generated by Django 3.1.2 on 2020-10-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_contenido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='contenedor',
        ),
        migrations.AddField(
            model_name='booklist',
            name='booklistsContenidos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_booklist_booklistsContenidos_+', to='manejador_contenido.Booklist'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='contenidos',
            field=models.ManyToManyField(blank=True, null=True, to='manejador_contenido.Contenido'),
        ),
    ]
