# Generated by Django 3.1.2 on 2020-10-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_contenido', '0002_auto_20201011_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='contenidos',
            field=models.ManyToManyField(blank=True, to='manejador_contenido.Contenido'),
        ),
    ]
