# Generated by Django 3.1.2 on 2020-10-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_contenido', '0003_auto_20201011_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='booklistsContenidos',
            field=models.ManyToManyField(blank=True, related_name='_booklist_booklistsContenidos_+', to='manejador_contenido.Booklist'),
        ),
    ]
