# Generated by Django 3.1.2 on 2020-10-16 02:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BR', 'Booklist por rango'), ('BP', 'Booklist promedio'), ('BC', 'Booklist por carrera')], max_length=2)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('estadistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklick.estadistica')),
            ],
        ),
    ]
