# Generated by Django 2.2 on 2020-10-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='lista_actividad',
            field=models.TextField(),
        ),
    ]
