# Generated by Django 2.2 on 2020-10-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklick', '0002_auto_20201002_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='lista_actividad',
            field=models.CharField(max_length=50),
        ),
    ]
