# Generated by Django 3.1.2 on 2020-10-12 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('intereses', models.TextField()),
                ('carrera', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manejador_usuarios.universidad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
