# Generated by Django 3.1.2 on 2020-10-09 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='universidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manejador_usuarios.universidad'),
            preserve_default=False,
        ),
    ]
