# Generated by Django 3.1.2 on 2020-10-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manejador_usuarios', '0002_auto_20201008_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
